apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  # environment variables and values present in the container
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306" # default port for MySQL
